apiVersion: batch/v1
kind: Job
metadata:
  name: link-secret-to-sa
  namespace: {{ .Values.global.cicd.namespaces }}
  annotations:
    argocd.argoproj.io/hook: "PostSync"
spec:
  template:
    spec:
      containers:
      - name: secrets-link
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli
        command: ["oc", "secret", "link", "pipeline", "git-secret"]
      restartPolicy: Never
      serviceAccount: pipeline
  backoffLimit: 4
