apiVersion: v1
kind: Secret
metadata:
  name: roxsecrets
  namespace: {{ .Values.global.cicd.namespace }}
stringData:
  rox_central_endpoint: central-stackrox.{{ .Values.global.hubClusterDomain }}:443